### ISSUE TITLE
build failure for iotedge-cli

### ISSUE THREAD

**Issue by yoctotutor** [ASUS-IPC/meta-iotedge#2]
I followed this doc for setup asus iot pe100a yocto build,
**https://github.com/ASUS-IPC/manifest  
yocto-3.2-imx_8m-HED.xml**

getting below error,

```
dell@dell:/source/build_imx8mq-pe100a$ bitbake imx-image-full
NOTE: Your conf/bblayers.conf has been automatically updated.
Loading cache: 100% |                                                                                             | ETA:  --:--:--
Loaded 0 entries from dependency cache.
WARNING: /source/sources/meta-iotedge/recipes-core/iotedge-cli/iotedge-cli_1.1.3.bb: Exception during build_dependencies for AUTOREV
WARNING: /source/sources/meta-iotedge/recipes-core/iotedge-cli/iotedge-cli_1.1.3.bb: Error during finalise of /source/sources/meta-iotedge/recipes-core/iotedge-cli/iotedge-cli_1.1.3.bb
ERROR: ExpansionError during parsing /source/sources/meta-iotedge/recipes-core/iotedge-cli/iotedge-cli_1.1.3.bb
Traceback (most recent call last):
  File "/source/sources/poky/bitbake/lib/bb/fetch2/git.py", line 231, in Git.urldata_init(ud=<bb.fetch2.FetchData object at 0x7f18f313c460>, d=<bb.data_smart.DataSmart object at 0x7f18f442d310>):
     
    >        ud.setup_revisions(d)
     
  File "/source/sources/poky/bitbake/lib/bb/fetch2/__init__.py", line 1312, in FetchData.setup_revisions(d=<bb.data_smart.DataSmart object at 0x7f18f442d310>):
             for name in self.names:
    >            self.revisions[name] = srcrev_internal_helper(self, d, name)
     
  File "/source/sources/poky/bitbake/lib/bb/fetch2/__init__.py", line 1177, in srcrev_internal_helper(ud=<bb.fetch2.FetchData object at 0x7f18f313c460>, d=<bb.data_smart.DataSmart object at 0x7f18f442d310>, name='hyperlocal-windows'):
         if srcrev == "AUTOINC":
    >        srcrev = ud.method.latest_revision(ud, d, name)
     
  File "/source/sources/poky/bitbake/lib/bb/fetch2/__init__.py", line 1582, in Git.latest_revision(ud=<bb.fetch2.FetchData object at 0x7f18f313c460>, d=<bb.data_smart.DataSmart object at 0x7f18f442d310>, name='hyperlocal-windows'):
             except KeyError:
    >            revs[key] = rev = self._latest_revision(ud, d, name)
                 return rev
  File "/source/sources/poky/bitbake/lib/bb/fetch2/git.py", line 655, in Git._latest_revision(ud=<bb.fetch2.FetchData object at 0x7f18f313c460>, d=<bb.data_smart.DataSmart object at 0x7f18f442d310>, name='hyperlocal-windows'):
                         return sha1
    >        raise bb.fetch2.FetchError("Unable to resolve '%s' in upstream git repository in git ls-remote output for %s" % \
                 (ud.unresolvedrev[name], ud.host+ud.path))
bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure: Unable to resolve 'master' in upstream git repository in git ls-remote output for github.com/Azure/hyperlocal-windows


Summary: There were 2 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
```

**Comment by harryliou** [comment]
Hi @yoctotutor 
The build failed because some resources branch names were changed from master to main.
Refer to [PR](https://github.com/Azure/meta-iotedge/pull/79/files) to manually fix.

Thanks for the report and will fix it asap!

**Comment by asus-leslieyu** [comment]
Fix is pushed.
https://github.com/ASUS-IPC/meta-iotedge/commits/yocto-3.2-imx_8m-HED
